### ISSUE TITLE
[ERROR ] check had an unhandled error: check_nearfull

### ISSUE THREAD

**Issue by GillesMocellin** [ceph/ceph-medic#149]
On my Lab cluster, I have one node which failed with the following error.
There is a difference, that OSD node is Ubuntu 18.04, the others Ubuntu 16.04. All with Ceph 13.2.8 community packages.

[2020-03-13 09:27:42,234][fidcllabs-sto-04.labs.fidcl.cloud][INFO  ] Running command: sudo ceph 
osd dump --format json
[2020-03-13 09:27:43,486][ceph_medic.runner][ERROR ] check had an unhandled error: check_nearfull
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ceph_medic/runner.py", line 77, in run_cluster
    result = getattr(module, check)()
  File "/usr/local/lib/python2.7/dist-packages/ceph_medic/checks/cluster.py", line 25, in check_nearfull
    if osd_map['nearfull']:
KeyError: 'nearfull'

**Comment by Dannyb48** [comment]
I got this same issue. There is no difference in OS version in my case.
